### ISSUE TITLE
Implementing debounce for Signals

### ISSUE THREAD

**Issue by bbarker** [purescript-concur/purescript-concur-core#2]
I started taking a look at debounce, e.g. as described in the comment below the comment below:

```purescript
-- Can base off of: https://github.com/component/debounce/blob/master/index.js
debounce :: forall a. Milliseconds -> Boolean -> Signal a -> Signal a
debounce t i s = do
  timestamp <- justEffect (time initDate) nowDateTime pure
```

I didn't get very far because the question of how an API like [setTimeout](https://pursuit.purescript.org/packages/purescript-js-timers/4.0.1/docs/Effect.Timer#v:setTimeout) should work with `Signal` isn't clear to me. Do we need our own FFI to interface with the JS `setTimeout` etc?

**Comment by bbarker** [comment]
Hi @ajnsit  - just a friendly ping for when you have time to think about this, thanks!

**Comment by ajnsit** [comment]
Ah that's an interesting usecase. I just added a [`debounce` function to `Concur.Core.FRP`](https://github.com/purescript-concur/purescript-concur-core/commit/d9ccc5df645b5ca71288b477bfe0355064f87993).

It's fairly simple, it looks like this -

```purescript
-- Debounced output from a widget
-- wrapped into a signal
debounce :: forall a v. Monoid v => Number -> a -> (a -> Widget v a) -> Signal v a
debounce timeoutMs ainit winit = go ainit winit
  where
    go a w = step a (go' a w)
    go' a w = do
      res <- (Just <$> w a) <|> (Nothing <$ liftAff (delay (Milliseconds timeoutMs)))
      case res of
        -- Timeout fired
        Nothing -> pure (go a w)
        -- Events fired, but we are still in timeout
        Just a' -> go' a' w
```

You can use it to wrap widgets in a similar manner as `loopW`, but the output would be debounced. For example -

```purescript
-- Widget to count up or down
clickW :: Int -> Widget HTML Int
clickW n = div'
  [ n+1 <$ button [onClick] [text ("Increment this count -> " <> show n)]
  , n-1 <$ button [onClick] [text ("Decrement this count -> " <> show n)]
  ]

-- Debounced click widget as a signal
clickS :: Int -> Signal HTML Int
clickS n = debounce 500.0 n clickW
```

Let me know if that works for you!

**Comment by bbarker** [comment]
@ajnsit Thanks - I'll try to go over your code soon to understand it better. It doesn't seem to quite work yet for my use case, in tht it seems to reset the textInput fields whenever the debounce timer fires, e.g., when used like this, as in [this branch](https://github.com/labordynamicsinstitute/metajelo-ui/tree/debounce):

```purescript
textInputWidget :: String -> Widget HTML String
textInputWidget txt =
  D.input [P.value txt, P.unsafeTargetValue <$> P.onChange]

textInput' :: D.El' -> String -> CtrlSignal HTML String
textInput' tag label initVal = labelSig' tag label [] $ sig initVal
  where
    sig :: String -> Signal HTML String
    sig txt = debounce 500.0 txt textInputWidget

-- | Reasonable defaults for filtering input text
textFilter :: Signal HTML String -> Signal HTML (Maybe NonEmptyString)
textFilter txtSig = do
  txt <- txtSig
  pure $ fromString $ trim txt

textInput :: D.El' -> String -> CtrlSignal HTML (Maybe NonEmptyString)
textInput tag label iVal = textFilter $ textInput' tag label
  (foldf toString iVal)
```

**Comment by bbarker** [comment]
OK, agreed that code is pretty clear! I haven't used `Aff` before but seems straightforward in this case.

For the widget to not lose its state it needs to be controlled, which certainly seems to be the case here: `a` or the updated `a'` is always passed into the signal, and in my case, `textInputWidget` is also controlled at the widget level thanks to using `P.value txt` ... hmmm.

**Comment by bbarker** [comment]
@ajnsit Just wanted to check if the `textInput` example I provided makes sense, and if it is also an issue for you to use `debounce` with it, as it is for me.

**Comment by ajnsit** [comment]
@bbarker Apologies for the late response. I wasn't able to reproduce the issue. Also, it's hard for me to run the full code in the metajelo repo, so providing an small isolated example that reproduces the issue would greatly speed up my response.

I created a small example that seems to work fine on my system. Can you check if it works for you?

https://gist.github.com/ajnsit/454c9432cd0cdcb10a846f88260a7053

**Comment by bbarker** [comment]
@ajnsit Thanks, I should have constructed the example; yours works for `mainWidget`; all I had to do was drop `mainWidget` into my codebase and was surprised to see it did work as expected. I'll try to create a fairly small example demonstrating the issue.

> Also, it's hard for me to run the full code in the metajelo repo

I tried to make sure it was easy to build and run, so if you've encountered any issues here, I'd love the feedback.

**Comment by ajnsit** [comment]
> I tried to make sure it was easy to build and run, so if you've encountered any issues here, I'd love the feedback.

Well, this is what I get on `npm install && npm run build && npm run start` -

```
metajelo-ui/static/index.js:3:29: Cannot resolve dependency './index.opt.js' at 'metajelo-ui/static/index.opt.js'
  1 | // var Metajelo = require("../output/Metajelo"); // For bower
  2 |
> 3 | import * as MetajeloUI from  "./index.opt.js";
    |                             ^
  4 | window.MetajeloUI = MetajeloUI;
```

**Comment by bbarker** [comment]
@ajnsit I see, in https://github.com/labordynamicsinstitute/metajelo-ui#building I note to use `npm run prod`, I hadn't been using `npm run start` but neglected to remove it from `scripts`; `prod` builds it without launching, `debug` is like prod but doesn't minify; would you suggest just renaming `debug` to `start` so `npm run start` would work as people expect, or is there some other behavior expected of `start`? 


Also, I'm presently looking into this more, but have yet to determine the issue, still have some things to try.

**Comment by ajnsit** [comment]
I would expect `npm run start` to start a development server, which watches the JS sources and reloads the app automatically whenever there is a change.

Then while developing, I can make changes to the PS code in the IDE, which automatically triggers a build via psc-ide, which automatically triggers the development server to load the new code and refresh the webpage in the browser. I don't even need to bring the browser window to the foreground to see the impact of my changes as I type them, no need to even save the file!

You can see the behaviour in action in say the [purescript-concur-starter](https://github.com/purescript-concur/purescript-concur-starter) repo. The README has more instructions.

**Comment by bbarker** [comment]
@ajnsit Great, I'll take a look at that soon and get my repo builds updated.

On another note, I found a minimal example that demonstrates the issue:

```purescript
mainWidget :: forall a. Widget HTML a
mainWidget = dyn $ do
  s1 <- textInput D.div' "HELLO" Nothing
  s2 <- textInput D.div' "GOODBYE" Nothing
  display (D.div' [D.text $ (show s1) <> (show s2)])
```

It occurs when you have two debounced widgets.

**Comment by bbarker** [comment]
Another datapoint that is a bit odd; if I change the example slightly like this where `textInput2` is NOT debounced:

```purescript
mainWidget :: forall a. Widget HTML a
mainWidget = dyn $ do
  s1 <- textInput D.div' "HELLO" Nothing
  s2 <- textInput2 D.div' "GOODBYE" Nothing
  display (D.div' [D.text $ (show s1) <> (show s2)])
```

The non-debounced entry and value is the one that is reset on the debounce interval.

So a variant of the issue exists even one when of the text inputs is not debounced.

**Comment by bbarker** [comment]
@ajnsit Actually, do think this issue is more to do with concur itself, or with how react, or some interaction between the two?

**Comment by bbarker** [comment]
Hi @ajnsit , just wanted to check to see if you'd had a chance to look at the minimal examples I posted above demonstrating the issue with debounce.

**Comment by ajnsit** [comment]
Hi @bbarker, I finally tracked down this bug. The debounce widget was badly written. I have now fixed it.

Debounce, as it was written, immediately started the timer when the widget was created. And on timeout, it emitted the value and restarted. This caused the widget to keep emitting values at regular intervals even when the text contents had not changed.

Consider all the cases -

1. When we had a single debounced widget, a reflow was not detectable since there was no other widget which was affected.

2. With another widget downstream of the debounced widget, that widget got reset everytime the timer fired.

3. If the downstream widget was also debounced, then it would also fire periodically, which would in turn loop around and reset the first widget! Hence we would get all widgets resetting.

Please let me know if you are still facing this issue after getting the new `debounce` code.

**Comment by bbarker** [comment]
You know, this makes perfect sense now that you've explained it.  I guess I'd been thinking `go'` was lazily evaluated by `step`, but now I think that shouldn't be possible in PureScript (but would be in Haskell, I thin).

**Comment by bbarker** [comment]
Unfortunately, this did not seem to work in the end. Despite looking into this, I was not able to really make any improvements.

When profiling in Chrome, [unstable_runWithPriority](https://www.reddit.com/r/reactjs/comments/gyudlk/react_internals_questions_what_react_api_uses/) from React seems to be taking up most of the time, so I think this indicates that events are getting through to react when they should be intercepted. 

Nate Faubion mentioned that "depending on how you are using it, racing against w a here https://github.com/purescript-concur/purescript-concur-core/blob/v0.4.2/src/Concur/Core/FRP.purs#L213 seems suspect", and I suppose I can see that `w a` may be running during that race. He also shared a Halogen example, though despite my attempts so far I've been unable to get much interesting working with Concur. 

I had a couple of other ideas - would `remoteWidget` or a related function be useful in this context?  Would it be possible to use Aff to somehow send all data from the widget to a buffer rather than having the widget return?

If you would like to see an example of the performance issue, go to https://labordynamicsinstitute.github.io/metajelo-web/ and click "Save XML". Then go to https://labordynamicsinstitute.github.io/metajelo-ui/, and in the first "browse" dialogue at the very top, upload the xml file you downloaded. This will populate the form. Then, start typing in any text box to observe or profile the performance issue.

**Comment by bbarker** [comment]
The other thought that I just fleshed out a bit more, that is really more of a workaround, relates to Props and an example I saw in your formless port:

```purescript
(F.asyncSetValidate debounceTime _email1 <<< P.unsafeTargetValue) <$> P.onChange
```

So if I could debounce directly at the props level, that would probably work for me. Not as elegant, but likely avoids triggering React in the same way as we're currently doing. I'll try to have a look at this approach soon.

**Comment by ajnsit** [comment]
@bbarker I see the performance issues on the webpage. What should I do to run this locally?

**Comment by bbarker** [comment]
@ajnsit after cloning the metajelo-ui project, with the standard tools installed you should be able to just do `npm install && npm run build && npm run prod`.  

There's also a container option for building, everything stays the same but with docker installed you can run `./psc.sh bash` to get a shell in the docker container with all the tools. See also [in the README](https://github.com/labordynamicsinstitute/metajelo-ui#building), and if I've left anything out in my instructions here (or there), do let me know!

Note: `npm run debug` should be the same as `npm run prod` bu without minificaiton.

**Comment by bbarker** [comment]
FWIW, here were my futile attempts to use the `AVar` approach: https://github.com/labordynamicsinstitute/metajelo-ui/commit/02baf911846ab7f7de2cc3b1ac0ecbe0b7a5e604

Basically, it has the expected behavior as written: the widget disappears while the debounce timer is on, cause that's what widgets do in Concur of course! That's why I was thinking maybe running it as a never-ending remote widget might be promising.

Still, after profiling the above code, the performance was still quite bad, but for apparently different reasons according to the chromium profiler - I saw lots of recursive anonymous function calls being fired when entering text, but not `unstable_runWithPriority`.

**Comment by ajnsit** [comment]
Is this really a debounce issue? I just ran the code and changed `textInput'` to be the following, and I still see the same issue. Something else seems to be causing this.

```purescript
textInput' :: CtrlSignal HTML String
textInput' initVal = loopW initVal textInputWidget
```

**Comment by ajnsit** [comment]
Okay, changing the definition of `textInputWidget` to use `defaultValue` instead of `value` fixes this.

```purescript
textInputWidget :: String -> Widget HTML String
textInputWidget txt =
  D.input [P.defaultValue txt, P.unsafeTargetValue <$> P.onChange]
```

Basically when you use `value`, the textbox does not updated until the value is changed in code which causes stuttering because rendering the entire tree structure (which seems to be rendering on every change) takes time. With `defaultValue`, we let the browser update the textbox which keeps it snappy, but the code just gets the changed values.

**Comment by bbarker** [comment]
@ajnsit Sorry, somehow I didn't see your last 2 comments until now - appreciate the quick feedback. Clearly I need to do something about my inbox.

I'm curious - were you able to see a noticeable improvement when loading the full xml file and then typing into an input field? For me it seems to be the same for me (also, I had tried this approach before, just to see if there was an effect). This time I went ahead and pushed the change to master so it would be [build and deployed](https://github.com/labordynamicsinstitute/metajelo-ui/commit/34934cdcd1cb4e30de51398f1e94997eb28888ac) by CI at https://labordynamicsinstitute.github.io/metajelo-ui/

I will note, that chrome-based browsers seem to have much better performance. In firefox-based browsers, the effect is far more noticeable.

**Comment by ajnsit** [comment]
I was trying in Chrome, but even in Firefox the performance is much improved compared to earlier. However it still does stutter. I'll take a further look.

**Comment by bbarker** [comment]
Closing this again - with high probability it doesn't seem to be related to debounce ( see https://github.com/purescript-concur/purescript-concur-core/issues/15#issuecomment-770083981). In particular, debounce would, I think, help prevent state from cascading through the app at a rapid pace, but even when state is isolated, this can be a problem in a large concur app.
