### ISSUE TITLE
No issue - just love ❤️ ❤️ 

### ISSUE THREAD

**Issue by drshade** [purescript-concur/purescript-concur-core#23]
Just wanted to drop a note that i absolutely love this web framework and it makes me happy. I've written a handful of small fun projects using it and i absolutely adore it. It is small, fast, easy and productive, but also a fantastic way to show real tangible example of pure functional programming using monads for effect / async to people people who are comfortable with more mainstream web programming.

Thank you for making it - and also in advance for continuing to support it!

**Comment by ajnsit** [comment]
This made my day! Thanks for using Concur and providing feedback @drshade!

**Comment by MiracleBlue** [comment]
Same here actually, this is the most unique and interesting web framework idea I've seen since React first came along.  This generator-like approach has given me several "wow" moments.  It's my preferred Purescript UI framework now, easily!  Thanks @ajnsit !
