### ISSUE TITLE
question about potential Cofree conflict

### ISSUE THREAD

**Issue by bbarker** [purescript-concur/purescript-concur-core#9]
This isn't an issue I've actually encountered, but I wonder what might happen if a user wishes to make use of both the `Cofree` implemented here and in the "standard" package. IIRC that would create a compile-time resolution error at best. I'm reminded of Haskell's Strict vs Lazy data structures for string-related things, like Lazy.Text and Text. I wonder if assigning a unique namespace would be the way to go here as well.

**Comment by ajnsit** [comment]
Yeah that's true. Since Cofree is internal to Concur, I don't think it should be a problem to rename the module. I will do that.

**Comment by ajnsit** [comment]
Oh, actually the module is already named `Control.Cofree` while the official module is in `Control.Comonad.Cofree`. So there should be no conflict.

**Comment by bbarker** [comment]
Ohv sorry ... It sounded very official!
